### ISSUE TITLE
Humidity Always 0% on Main Site, But Correct On /metrics

### ISSUE THREAD

**Issue by efaden** [akhenakh/acurite_to_graph#1] opened 2017-06-23 00:36 UTC
Thoughts?

**Comment by akhenakh** [comment] 2017-06-26 14:06
I can confirm the bug, I don't use the web frontend enough.

should be an easy fix since as you mentioned the data are correct inside prometheus.

**Comment by akhenakh** [comment] 2017-10-30 02:52
fixed in latest updates

**Closed as completed by akhenakh** 2017-10-30 02:52 UTC
